name: Keep Backend Alive

on:
    schedule:
        # Runs every 10 minutes
        - cron: "*/10 * * * *"
    workflow_dispatch: # Allows manual triggering

jobs:
    ping:
        runs-on: ubuntu-latest

        steps:
            - name: Ping Backend Health Check
              run: |
                  echo "Pinging backend at $(date)"
                  response=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.BACKEND_URL }}/api/health)
                  echo "Response code: $response"

                  if [ $response -eq 200 ]; then
                    echo "✅ Backend is alive and responding"
                  else
                    echo "⚠️ Backend returned status code: $response"
                    exit 1
                  fi

            - name: Log Status
              if: always()
              run: echo "Keep-alive ping completed at $(date)"
